/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContentTypeBuilderGetComponents200Response } from '../model/models';
import { ContentTypeBuilderGetComponentsByUid200Response } from '../model/models';
import { ContentTypeBuilderGetContentTypes200Response } from '../model/models';
import { ContentTypeBuilderGetContentTypesByUid200Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ContentTypeBuilderGetComponentsByUidRequestParams {
    uid: string;
}

export interface ContentTypeBuilderGetContentTypesRequestParams {
    kind: 'collectionType' | 'singleType';
}

export interface ContentTypeBuilderGetContentTypesByUidRequestParams {
    uid: string;
}


export interface ContentTypeBuilderServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    contentTypeBuilderGetComponents(extraHttpRequestParams?: any): Observable<ContentTypeBuilderGetComponents200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    contentTypeBuilderGetComponentsByUid(requestParameters: ContentTypeBuilderGetComponentsByUidRequestParams, extraHttpRequestParams?: any): Observable<ContentTypeBuilderGetComponentsByUid200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    contentTypeBuilderGetContentTypes(requestParameters: ContentTypeBuilderGetContentTypesRequestParams, extraHttpRequestParams?: any): Observable<ContentTypeBuilderGetContentTypes200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    contentTypeBuilderGetContentTypesByUid(requestParameters: ContentTypeBuilderGetContentTypesByUidRequestParams, extraHttpRequestParams?: any): Observable<ContentTypeBuilderGetContentTypesByUid200Response>;

}
