/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProjectDeleteProjectsById200Response } from '../model/models';
import { ProjectGetProjects200Response } from '../model/models';
import { ProjectGetProjectsById200Response } from '../model/models';
import { ProjectGetProjectsPaginationParameter } from '../model/models';
import { ProjectGetProjectsPopulateParameter } from '../model/models';
import { ProjectGetProjectsSortParameter } from '../model/models';
import { ProjectPostProjects200Response } from '../model/models';
import { ProjectPostProjectsRequest } from '../model/models';
import { ProjectPutProjectsById200Response } from '../model/models';
import { ProjectPutProjectsByIdRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ProjectDeleteProjectsByIdRequestParams {
    id: string;
    fields?: Array<'title' | 'type' | 'category' | 'description' | 'tags' | 'createdAt' | 'updatedAt' | 'publishedAt'>;
    populate?: ProjectGetProjectsPopulateParameter;
    filters?: { [key: string]: any; };
    status?: 'draft' | 'published';
}

export interface ProjectGetProjectsRequestParams {
    fields?: Array<'title' | 'type' | 'category' | 'description' | 'tags' | 'createdAt' | 'updatedAt' | 'publishedAt'>;
    filters?: { [key: string]: any; };
    q?: string;
    pagination?: ProjectGetProjectsPaginationParameter;
    sort?: ProjectGetProjectsSortParameter;
    populate?: ProjectGetProjectsPopulateParameter;
    status?: 'draft' | 'published';
}

export interface ProjectGetProjectsByIdRequestParams {
    id: string;
    fields?: Array<'title' | 'type' | 'category' | 'description' | 'tags' | 'createdAt' | 'updatedAt' | 'publishedAt'>;
    populate?: ProjectGetProjectsPopulateParameter;
    filters?: { [key: string]: any; };
    sort?: ProjectGetProjectsSortParameter;
    status?: 'draft' | 'published';
}

export interface ProjectPostProjectsRequestParams {
    fields?: Array<'title' | 'type' | 'category' | 'description' | 'tags' | 'createdAt' | 'updatedAt' | 'publishedAt'>;
    populate?: ProjectGetProjectsPopulateParameter;
    status?: 'draft' | 'published';
    projectPostProjectsRequest?: ProjectPostProjectsRequest;
}

export interface ProjectPutProjectsByIdRequestParams {
    id: string;
    fields?: Array<'title' | 'type' | 'category' | 'description' | 'tags' | 'createdAt' | 'updatedAt' | 'publishedAt'>;
    populate?: ProjectGetProjectsPopulateParameter;
    status?: 'draft' | 'published';
    projectPutProjectsByIdRequest?: ProjectPutProjectsByIdRequest;
}


export interface ProjectServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    projectDeleteProjectsById(requestParameters: ProjectDeleteProjectsByIdRequestParams, extraHttpRequestParams?: any): Observable<ProjectDeleteProjectsById200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    projectGetProjects(requestParameters: ProjectGetProjectsRequestParams, extraHttpRequestParams?: any): Observable<ProjectGetProjects200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    projectGetProjectsById(requestParameters: ProjectGetProjectsByIdRequestParams, extraHttpRequestParams?: any): Observable<ProjectGetProjectsById200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    projectPostProjects(requestParameters: ProjectPostProjectsRequestParams, extraHttpRequestParams?: any): Observable<ProjectPostProjects200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    projectPutProjectsById(requestParameters: ProjectPutProjectsByIdRequestParams, extraHttpRequestParams?: any): Observable<ProjectPutProjectsById200Response>;

}
