/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProjectGetProjectsPaginationParameter } from '../model/models';
import { UploadGetFiles200ResponseInner } from '../model/models';
import { UploadGetFilesFieldsParameter } from '../model/models';
import { UploadGetFilesPopulateParameter } from '../model/models';
import { UploadGetFilesSortParameter } from '../model/models';
import { UploadPost200Response } from '../model/models';
import { UploadPost200ResponseAnyOf } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface UploadDeleteFilesByIdRequestParams {
    id: number;
}

export interface UploadGetFilesRequestParams {
    fields?: UploadGetFilesFieldsParameter;
    populate?: UploadGetFilesPopulateParameter;
    sort?: UploadGetFilesSortParameter;
    pagination?: ProjectGetProjectsPaginationParameter;
    filters?: { [key: string]: any; };
}

export interface UploadGetFilesByIdRequestParams {
    id: number;
    fields?: UploadGetFilesFieldsParameter;
    populate?: UploadGetFilesPopulateParameter;
}

export interface UploadPostRequestParams {
    id?: number;
}


export interface UploadServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    uploadDeleteFilesById(requestParameters: UploadDeleteFilesByIdRequestParams, extraHttpRequestParams?: any): Observable<UploadPost200ResponseAnyOf>;

    /**
     * 
     * 
* @param requestParameters
     */
    uploadGetFiles(requestParameters: UploadGetFilesRequestParams, extraHttpRequestParams?: any): Observable<Array<UploadGetFiles200ResponseInner>>;

    /**
     * 
     * 
* @param requestParameters
     */
    uploadGetFilesById(requestParameters: UploadGetFilesByIdRequestParams, extraHttpRequestParams?: any): Observable<UploadPost200ResponseAnyOf>;

    /**
     * 
     * 
* @param requestParameters
     */
    uploadPost(requestParameters: UploadPostRequestParams, extraHttpRequestParams?: any): Observable<UploadPost200Response>;

}
