/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProjectGetProjectsPaginationParameter } from '../model/models';
import { UploadGetFilesFieldsParameter } from '../model/models';
import { UploadGetFilesPopulateParameter } from '../model/models';
import { UploadGetFilesSortParameter } from '../model/models';
import { UsersPermissionsGetPermissions200Response } from '../model/models';
import { UsersPermissionsGetRoles200Response } from '../model/models';
import { UsersPermissionsGetRolesById200Response } from '../model/models';
import { UsersPermissionsPostAuthChangePasswordRequest } from '../model/models';
import { UsersPermissionsPostAuthForgotPassword200Response } from '../model/models';
import { UsersPermissionsPostAuthForgotPasswordRequest } from '../model/models';
import { UsersPermissionsPostAuthLocal200Response } from '../model/models';
import { UsersPermissionsPostAuthLocalRegister200Response } from '../model/models';
import { UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUser } from '../model/models';
import { UsersPermissionsPostAuthLocalRegisterRequest } from '../model/models';
import { UsersPermissionsPostAuthLocalRequest } from '../model/models';
import { UsersPermissionsPostAuthResetPasswordRequest } from '../model/models';
import { UsersPermissionsPostAuthSendEmailConfirmation200Response } from '../model/models';
import { UsersPermissionsPostRolesRequest } from '../model/models';
import { UsersPermissionsPostUsers200Response } from '../model/models';
import { UsersPermissionsPostUsersRequest } from '../model/models';
import { UsersPermissionsPutRolesByRoleRequest } from '../model/models';
import { UsersPermissionsPutUsersByIdRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface UsersPermissionsDeleteRolesByRoleRequestParams {
    role: string;
}

export interface UsersPermissionsDeleteUsersByIdRequestParams {
    id: string;
}

export interface UsersPermissionsGetAuthByProviderCallbackRequestParams {
    provider: string;
}

export interface UsersPermissionsGetRolesByIdRequestParams {
    id: string;
}

export interface UsersPermissionsGetUsersRequestParams {
    fields?: UploadGetFilesFieldsParameter;
    populate?: UploadGetFilesPopulateParameter;
    sort?: UploadGetFilesSortParameter;
    pagination?: ProjectGetProjectsPaginationParameter;
    filters?: { [key: string]: any; };
}

export interface UsersPermissionsGetUsersByIdRequestParams {
    id: string;
    fields?: UploadGetFilesFieldsParameter;
    populate?: UploadGetFilesPopulateParameter;
}

export interface UsersPermissionsGetUsersCountRequestParams {
    filters?: { [key: string]: any; };
}

export interface UsersPermissionsGetUsersMeRequestParams {
    fields?: UploadGetFilesFieldsParameter;
    populate?: UploadGetFilesPopulateParameter;
}

export interface UsersPermissionsPostAuthChangePasswordRequestParams {
    usersPermissionsPostAuthChangePasswordRequest?: UsersPermissionsPostAuthChangePasswordRequest;
}

export interface UsersPermissionsPostAuthForgotPasswordRequestParams {
    usersPermissionsPostAuthForgotPasswordRequest?: UsersPermissionsPostAuthForgotPasswordRequest;
}

export interface UsersPermissionsPostAuthLocalRequestParams {
    usersPermissionsPostAuthLocalRequest?: UsersPermissionsPostAuthLocalRequest;
}

export interface UsersPermissionsPostAuthLocalRegisterRequestParams {
    usersPermissionsPostAuthLocalRegisterRequest?: UsersPermissionsPostAuthLocalRegisterRequest;
}

export interface UsersPermissionsPostAuthResetPasswordRequestParams {
    usersPermissionsPostAuthResetPasswordRequest?: UsersPermissionsPostAuthResetPasswordRequest;
}

export interface UsersPermissionsPostAuthSendEmailConfirmationRequestParams {
    usersPermissionsPostAuthForgotPasswordRequest?: UsersPermissionsPostAuthForgotPasswordRequest;
}

export interface UsersPermissionsPostRolesRequestParams {
    usersPermissionsPostRolesRequest?: UsersPermissionsPostRolesRequest;
}

export interface UsersPermissionsPostUsersRequestParams {
    usersPermissionsPostUsersRequest?: UsersPermissionsPostUsersRequest;
}

export interface UsersPermissionsPutRolesByRoleRequestParams {
    role: string;
    usersPermissionsPutRolesByRoleRequest?: UsersPermissionsPutRolesByRoleRequest;
}

export interface UsersPermissionsPutUsersByIdRequestParams {
    id: string;
    usersPermissionsPutUsersByIdRequest?: UsersPermissionsPutUsersByIdRequest;
}


export interface UsersPermissionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsDeleteRolesByRole(requestParameters: UsersPermissionsDeleteRolesByRoleRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthForgotPassword200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsDeleteUsersById(requestParameters: UsersPermissionsDeleteUsersByIdRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostUsers200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsGetAuthByProviderCallback(requestParameters: UsersPermissionsGetAuthByProviderCallbackRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthLocal200Response>;

    /**
     * 
     * 
*/
    usersPermissionsGetAuthEmailConfirmation(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    usersPermissionsGetConnect(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    usersPermissionsGetPermissions(extraHttpRequestParams?: any): Observable<UsersPermissionsGetPermissions200Response>;

    /**
     * 
     * 
*/
    usersPermissionsGetRoles(extraHttpRequestParams?: any): Observable<UsersPermissionsGetRoles200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsGetRolesById(requestParameters: UsersPermissionsGetRolesByIdRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsGetRolesById200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsGetUsers(requestParameters: UsersPermissionsGetUsersRequestParams, extraHttpRequestParams?: any): Observable<Array<UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUser>>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsGetUsersById(requestParameters: UsersPermissionsGetUsersByIdRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostUsers200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsGetUsersCount(requestParameters: UsersPermissionsGetUsersCountRequestParams, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsGetUsersMe(requestParameters: UsersPermissionsGetUsersMeRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostUsers200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostAuthChangePassword(requestParameters: UsersPermissionsPostAuthChangePasswordRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthLocal200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostAuthForgotPassword(requestParameters: UsersPermissionsPostAuthForgotPasswordRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthForgotPassword200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostAuthLocal(requestParameters: UsersPermissionsPostAuthLocalRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthLocal200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostAuthLocalRegister(requestParameters: UsersPermissionsPostAuthLocalRegisterRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthLocalRegister200Response>;

    /**
     * 
     * 
*/
    usersPermissionsPostAuthLogout(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    usersPermissionsPostAuthRefresh(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostAuthResetPassword(requestParameters: UsersPermissionsPostAuthResetPasswordRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthLocal200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostAuthSendEmailConfirmation(requestParameters: UsersPermissionsPostAuthSendEmailConfirmationRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthSendEmailConfirmation200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostRoles(requestParameters: UsersPermissionsPostRolesRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthForgotPassword200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPostUsers(requestParameters: UsersPermissionsPostUsersRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostUsers200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPutRolesByRole(requestParameters: UsersPermissionsPutRolesByRoleRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostAuthForgotPassword200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    usersPermissionsPutUsersById(requestParameters: UsersPermissionsPutUsersByIdRequestParams, extraHttpRequestParams?: any): Observable<UsersPermissionsPostUsers200Response>;

}
