/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf4 { 
  [key: string]: any | any;


    type: any | null;
    configurable?: any | null;
    _private?: any | null;
    pluginOptions?: { [key: string]: any; };
    targetField?: any | null;
}

