/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentTypeBuilderGetComponentsByUid200ResponseDataSchema } from './content-type-builder-get-components-by-uid200-response-data-schema';


export interface ContentTypeBuilderGetComponentsByUid200ResponseData { 
  [key: string]: any | any;


    uid: any | null;
    category: any | null;
    apiId: any | null;
    schema: ContentTypeBuilderGetComponentsByUid200ResponseDataSchema;
}

