/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPostProjects200ResponseDataId } from './project-post-projects200-response-data-id';


export interface ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf1 { 
  [key: string]: any | any;


    type: any | null;
    configurable?: any | null;
    _private?: any | null;
    pluginOptions?: { [key: string]: any; };
    relation: any | null;
    target: any | null;
    targetAttribute: ProjectPostProjects200ResponseDataId;
    autoPopulate?: any | null;
    mappedBy?: any | null;
    inversedBy?: any | null;
}

