/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPostProjects200ResponseDataId } from './project-post-projects200-response-data-id';
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf } from './content-type-builder-get-content-types-by-uid200-response-data-schema-attributes-value-any-of';
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf1 } from './content-type-builder-get-content-types-by-uid200-response-data-schema-attributes-value-any-of1';
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf2 } from './content-type-builder-get-content-types-by-uid200-response-data-schema-attributes-value-any-of2';
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf3 } from './content-type-builder-get-content-types-by-uid200-response-data-schema-attributes-value-any-of3';
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf4 } from './content-type-builder-get-content-types-by-uid200-response-data-schema-attributes-value-any-of4';
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf5 } from './content-type-builder-get-content-types-by-uid200-response-data-schema-attributes-value-any-of5';


export interface ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValue { 
    type: any | null;
    configurable?: any | null;
    _private?: any | null;
    pluginOptions?: { [key: string]: any; };
    multiple: any | null;
    required?: any | null;
    allowedTypes?: any | null;
    relation: any | null;
    target: any | null;
    targetAttribute: ProjectPostProjects200ResponseDataId;
    autoPopulate?: any | null;
    mappedBy?: any | null;
    inversedBy?: any | null;
    component: any | null;
    repeatable: any | null;
    min?: ProjectPostProjects200ResponseDataId;
    max?: ProjectPostProjects200ResponseDataId;
    components: any | null;
    targetField?: any | null;
    unique?: any | null;
    _default?: any | null;
    minLength?: any | null;
    maxLength?: any | null;
    _enum?: any | null;
    regex?: any | null;
}

