/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValue } from './content-type-builder-get-content-types-by-uid200-response-data-schema-attributes-value';
import { ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaRestrictRelationsTo } from './content-type-builder-get-content-types-by-uid200-response-data-schema-restrict-relations-to';


export interface ContentTypeBuilderGetContentTypesByUid200ResponseDataSchema { 
  [key: string]: any | any;


    displayName: any | null;
    singularName: any | null;
    pluralName: any | null;
    description: any | null;
    draftAndPublish: any | null;
    kind: ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaKindEnum | null;
    collectionName?: any | null;
    attributes: object;
    visible: any | null;
    restrictRelationsTo: ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaRestrictRelationsTo;
    pluginOptions?: { [key: string]: any; };
    options?: { [key: string]: any; };
    reviewWorkflows?: any | null;
    populateCreatorFields?: any | null;
    comment?: any | null;
    version?: any | null;
}
export enum ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaKindEnum {
    CollectionType = 'collectionType',
    SingleType = 'singleType'
};



