/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPostProjects200ResponseDataId } from './project-post-projects200-response-data-id';


export interface ContentTypeBuilderGetContentTypesByUid200ResponseDataSchemaAttributesValueAnyOf5 { 
  [key: string]: any | any;


    type: any | null;
    required?: any | null;
    unique?: any | null;
    _default?: any | null;
    min?: ProjectPostProjects200ResponseDataId;
    max?: ProjectPostProjects200ResponseDataId;
    minLength?: any | null;
    maxLength?: any | null;
    _enum?: any | null;
    regex?: any | null;
    _private?: any | null;
    configurable?: any | null;
    pluginOptions?: { [key: string]: any; };
}

