/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPostProjects200ResponseDataId } from './project-post-projects200-response-data-id';


export interface PluginUploadFileDocument { 
  [key: string]: any | any;


    /**
     * The document ID, represented by a UUID
     */
    documentId: any | null;
    id: ProjectPostProjects200ResponseDataId;
    /**
     * A string field
     */
    name: any | null;
    /**
     * A text field
     */
    alternativeText?: any | null;
    /**
     * A text field
     */
    caption?: any | null;
    /**
     * A JSON field
     */
    focalPoint?: any | null;
    /**
     * An integer field
     */
    width?: any | null;
    /**
     * An integer field
     */
    height?: any | null;
    /**
     * A JSON field
     */
    formats?: any | null;
    /**
     * A string field
     */
    hash: any | null;
    /**
     * A string field
     */
    ext?: any | null;
    /**
     * A string field
     */
    mime: any | null;
    /**
     * A decimal field
     */
    size: any | null;
    /**
     * A text field
     */
    url: any | null;
    /**
     * A text field
     */
    previewUrl?: any | null;
    /**
     * A string field
     */
    provider: any | null;
    /**
     * A JSON field
     */
    provider_metadata?: any | null;
    /**
     * A datetime field
     */
    createdAt?: any | null;
    /**
     * A datetime field
     */
    updatedAt?: any | null;
    /**
     * A datetime field
     */
    publishedAt: any | null;
    related: any | null;
}

