/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDeleteProjectsById200ResponseData } from './project-delete-projects-by-id200-response-data';


export interface ProjectDeleteProjectsById200Response { 
  [key: string]: any | any;


    data: ProjectDeleteProjectsById200ResponseData;
}

