/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pagination parameters
 */
export interface ProjectGetProjectsPaginationParameter { 
    /**
     * Include total count in response
     */
    withCount?: any | null;
    /**
     * Page number (1-based)
     */
    page: any | null;
    /**
     * Number of entries per page
     */
    pageSize: any | null;
    /**
     * Number of entries to skip
     */
    start: any | null;
    /**
     * Maximum number of entries to return
     */
    limit: any | null;
}

