/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectHyperlinkEntry { 
  [key: string]: any | any;


    /**
     * A string field
     */
    url: any | null;
    /**
     * A string field
     */
    icon: any | null;
    /**
     * An enum field
     */
    type: ProjectHyperlinkEntryTypeEnum | null;
}
export enum ProjectHyperlinkEntryTypeEnum {
    Github = 'Github',
    Documentation = 'Documentation',
    Other = 'Other'
};



