/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectPostProjectsRequestData { 
  [key: string]: any | any;


    /**
     * A string field
     */
    title: any | null;
    /**
     * An enum field
     */
    type: ProjectPostProjectsRequestDataTypeEnum | null;
    /**
     * A string field
     */
    category: any | null;
    /**
     * A text field
     */
    description: any | null;
    /**
     * A string field
     */
    tags?: any | null;
    /**
     * A datetime field
     */
    publishedAt: any | null;
    /**
     * A media field
     */
    coverImg?: any | null;
    /**
     * A component field
     */
    info?: any | null;
    /**
     * A component field
     */
    key_features?: any | null;
    /**
     * A dynamic zone field
     */
    blocks: any | null;
    /**
     * A component field
     */
    hyperlinks?: any | null;
}
export enum ProjectPostProjectsRequestDataTypeEnum {
    Projects = 'Projects',
    Academic = 'Academic'
};



