/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPostProjects200ResponseDataId } from './project-post-projects200-response-data-id';
import { PluginUploadFileDocument } from './plugin-upload-file-document';


export interface ProjectPostProjects200ResponseData { 
  [key: string]: any | any;


    /**
     * The document ID, represented by a UUID
     */
    documentId: any | null;
    id: ProjectPostProjects200ResponseDataId;
    /**
     * A string field
     */
    title: any | null;
    /**
     * An enum field
     */
    type: ProjectPostProjects200ResponseDataTypeEnum | null;
    /**
     * A string field
     */
    category: any | null;
    /**
     * A text field
     */
    description: any | null;
    /**
     * A string field
     */
    tags?: any | null;
    /**
     * A datetime field
     */
    createdAt?: any | null;
    /**
     * A datetime field
     */
    updatedAt?: any | null;
    /**
     * A datetime field
     */
    publishedAt: any | null;
    /**
     * A media field
     */
    coverImg?: PluginUploadFileDocument;
    /**
     * A component field
     */
    info?: any | null;
    /**
     * A component field
     */
    key_features?: any | null;
    /**
     * A dynamic zone field
     */
    blocks: any | null;
    /**
     * A component field
     */
    hyperlinks?: any | null;
}
export enum ProjectPostProjects200ResponseDataTypeEnum {
    Projects = 'Projects',
    Academic = 'Academic'
};



