/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectInfoEntry { 
  [key: string]: any | any;


    /**
     * A string field
     */
    label: any | null;
    /**
     * A string field
     */
    value: any | null;
    /**
     * An enum field
     */
    type: ProjectInfoEntryTypeEnum | null;
    /**
     * A string field
     */
    link?: any | null;
    /**
     * An integer field
     */
    order: any | null;
}
export enum ProjectInfoEntryTypeEnum {
    Contributor = 'Contributor',
    Plain = 'Plain',
    Status = 'Status'
};



