/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPostProjects200ResponseDataId } from './project-post-projects200-response-data-id';
import { UploadPost200ResponseAnyOfProviderMetadata } from './upload-post200-response-any-of-provider-metadata';


export interface UploadPost200ResponseAnyOf { 
  [key: string]: any | any;


    id: any | null;
    documentId: any | null;
    name: string;
    alternativeText?: ProjectPostProjects200ResponseDataId;
    caption?: ProjectPostProjects200ResponseDataId;
    width?: any | null;
    height?: any | null;
    formats?: { [key: string]: any; };
    hash: string;
    ext?: string;
    mime: string;
    size: any | null;
    url: string;
    previewUrl?: ProjectPostProjects200ResponseDataId;
    folder?: any | null;
    folderPath: string;
    provider: string;
    provider_metadata?: UploadPost200ResponseAnyOfProviderMetadata;
    createdAt: string;
    updatedAt: string;
    createdBy?: any | null;
    updatedBy?: any | null;
}

