/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsPostAuthLocal200ResponseUserRole } from './users-permissions-post-auth-local200-response-user-role';


export interface UsersPermissionsPostAuthLocal200ResponseUser { 
  [key: string]: any | any;


    id: any | null;
    documentId: string;
    username: string;
    email: string;
    provider: string;
    confirmed: any | null;
    blocked: any | null;
    role?: UsersPermissionsPostAuthLocal200ResponseUserRole;
    createdAt: string;
    updatedAt: string;
    publishedAt: string;
}

