/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUser } from './users-permissions-post-auth-local-register200-response-any-of-user';


export interface UsersPermissionsPostAuthLocalRegister200ResponseAnyOf1 { 
  [key: string]: any | any;


    user: UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUser;
}

