/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUser } from './users-permissions-post-auth-local-register200-response-any-of-user';
import { UsersPermissionsPostAuthLocalRegister200ResponseAnyOf1 } from './users-permissions-post-auth-local-register200-response-any-of1';
import { UsersPermissionsPostAuthLocalRegister200ResponseAnyOf } from './users-permissions-post-auth-local-register200-response-any-of';


export interface UsersPermissionsPostAuthLocalRegister200Response { 
    jwt: any | null;
    refreshToken?: any | null;
    user: UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUser;
}

