/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsPostAuthLocal200ResponseUser } from './users-permissions-post-auth-local200-response-user';


export interface UsersPermissionsPostAuthLocal200Response { 
  [key: string]: any | any;


    jwt: string;
    refreshToken?: string;
    user: UsersPermissionsPostAuthLocal200ResponseUser;
}

