/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUserRole } from './users-permissions-post-auth-local-register200-response-any-of-user-role';


export interface UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUser { 
  [key: string]: any | any;


    id: any | null;
    documentId: any | null;
    username: any | null;
    email: any | null;
    provider: any | null;
    confirmed: any | null;
    blocked: any | null;
    role?: UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUserRole;
    createdAt: any | null;
    updatedAt: any | null;
    publishedAt: any | null;
}

