/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersPermissionsPutRolesByRoleRequest { 
  [key: string]: any | any;


    name?: string;
    description?: string;
    type?: string;
    permissions?: { [key: string]: any; };
}

