/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsGetPermissions200ResponsePermissionsValue } from './users-permissions-get-permissions200-response-permissions-value';


export interface UsersPermissionsGetPermissions200Response { 
  [key: string]: any | any;


    permissions: object;
}

