/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersPermissionsPutUsersByIdRequest { 
  [key: string]: any | any;


    username?: string;
    email?: any | null;
    password?: string;
    role?: any | null;
}

