/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsGetRolesById200ResponseRole } from './users-permissions-get-roles-by-id200-response-role';


export interface UsersPermissionsGetRolesById200Response { 
  [key: string]: any | any;


    role: UsersPermissionsGetRolesById200ResponseRole;
}

