/**
 * portfolio-strapi
 * API documentation for portfolio-strapi v0.1.0
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectPostProjects200ResponseDataId } from './project-post-projects200-response-data-id';


export interface UsersPermissionsPostAuthLocalRegister200ResponseAnyOfUserRoleAnyOf { 
  [key: string]: any | any;


    id: any | null;
    name: any | null;
    description: ProjectPostProjects200ResponseDataId;
    type: any | null;
    createdAt: any | null;
    updatedAt: any | null;
}

